// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldcysiqmngaugwzfrsag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkY3lzaXFtbmdhdWd3emZyc2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NjI2MjEsImV4cCI6MjA1NDMzODYyMX0.iBfs3Mnf0HjLpjUTEuoYB9wU61U0oZG7lRAmONroAmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);